# Some options here require nightly.
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
wrap_comments = true
use_field_init_shorthand = true
# TODO: format_strings = true
# TODO: license_template_path
